app            = "vrg-app"
primary_region = "jnb"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    API_HOST = "vrg-api.internal:4000"

[http_service]
  internal_port        = 80
  force_https          = true
  auto_stop_machines   = "stop"
  auto_start_machines  = true
  min_machines_running = 0

[[vm]]
  memory   = "256mb"
  cpu_kind = "shared"
  cpus     = 1
